"""The city registry -- loaded and validated from data/cities.json.

This is the ONLY place a city is defined. `CITIES` used to be declared twice,
in docs/solar.js and in generate_ics_full.py, which meant adding a city was two
edits in two languages with nothing checking that the coordinates matched. At
33 cities that is untenable, so both sides now read from here: Python imports
this module, and docs/cities-data.js is generated by scripts/build_web.py.

Everything is validated on load rather than trusted, because the failure modes
are quiet ones:

  * a bad IANA zone name gives times that are silently an hour out for half the
    year -- ZoneInfo raises here instead
  * a swapped lat/lon still produces plausible-looking sunrise times
  * a duplicate or non-URL-safe key would corrupt a feed filename, and feed
    filenames are permanent once anyone subscribes

Paths are derived from this file's own location. The generator previously
carried absolute Windows paths, which meant it could not run on the VPS at all.
"""
import json
import re
from pathlib import Path
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "data"
DOCS = REPO / "docs"
CITIES_JSON = DATA / "cities.json"

KEY_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

LANGS = ("ar", "en")


def _fail(msg):
    raise ValueError(f"{CITIES_JSON.name}: {msg}")


def _load():
    raw = json.loads(CITIES_JSON.read_text(encoding="utf-8"))

    regions = raw["regions"]
    region_keys = set()
    for r in regions:
        if r["key"] in region_keys:
            _fail(f"duplicate region key {r['key']!r}")
        region_keys.add(r["key"])
        for lang in LANGS:
            if not r.get(lang, "").strip():
                _fail(f"region {r['key']!r} has no {lang} label")

    cities = {}
    for c in raw["cities"]:
        key = c["key"]
        if key in cities:
            _fail(f"duplicate city key {key!r}")
        if not KEY_RE.match(key):
            # Keys become feed filenames, and a feed URL can never be withdrawn.
            _fail(f"key {key!r} is not URL-safe (lowercase, digits, single hyphens)")
        if c["region"] not in region_keys:
            _fail(f"city {key!r} has unknown region {c['region']!r}")
        for lang in LANGS:
            if not c.get(lang, "").strip():
                _fail(f"city {key!r} has no {lang} name")
        if not -90.0 <= c["lat"] <= 90.0:
            _fail(f"city {key!r} latitude {c['lat']} out of range")
        if not -180.0 <= c["lon"] <= 180.0:
            _fail(f"city {key!r} longitude {c['lon']} out of range")
        try:
            ZoneInfo(c["tz"])
        except (ZoneInfoNotFoundError, ValueError):
            _fail(f"city {key!r} has unknown IANA timezone {c['tz']!r}")
        cities[key] = dict(c)

    if not any(c["feed"] for c in cities.values()):
        _fail("no city is marked feed:true -- the subscribe picker would be empty")

    return regions, cities


REGIONS, CITIES = _load()

#: Cities that currently have a generated .ics. The subscribe picker offers
#: only these, so it can never present a link that 404s.
FEED_CITIES = {k: c for k, c in CITIES.items() if c["feed"]}


def label(city_or_key, lang="ar"):
    """Display name of a city in the given language."""
    c = CITIES[city_or_key] if isinstance(city_or_key, str) else city_or_key
    return c[lang]


def by_region():
    """[(region_dict, [city_dict, ...]), ...] in the registry's own order."""
    return [(r, [c for c in CITIES.values() if c["region"] == r["key"]])
            for r in REGIONS]


if __name__ == "__main__":
    import sys
    # Arabic output on a cp1252 Windows console raises otherwise.
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    print(f"{len(CITIES)} cities in {len(REGIONS)} regions, all valid")
    for region, members in by_region():
        names = ", ".join(c["en"] for c in members)
        print(f"  {region['en']:<20} ({len(members)}) {names}")
    print(f"  feeds generated for: {', '.join(sorted(FEED_CITIES))}")
